USE test;

CREATE TABLE IF NOT EXISTS `log` (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `user_id` VARCHAR(36) DEFAULT NULL,
    `full_name` VARCHAR(256) DEFAULT NULL,
    `method` VARCHAR(8) DEFAULT NULL,
    `url` VARCHAR(256) DEFAULT NULL,
    `req_query` TEXT DEFAULT NULL,
    `req_params` TEXT DEFAULT NULL,
    `req_body` TEXT DEFAULT NULL,
    `res_body` TEXT DEFAULT NULL,
    `headers`  TEXT DEFAULT NULL,
    `ip` VARCHAR(36) DEFAULT NULL,
    `dateCreated` CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
