DROP DATABASE IF EXISTS cdi_db;

CREATE DATABASE IF NOT EXISTS cdi_db;
USE cdi_db;

CREATE TABLE IF NOT EXISTS `log` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `user_id` VARCHAR(36) DEFAULT NULL,
    `full_name` VARCHAR(256) DEFAULT NULL,
    `method` VARCHAR(8) DEFAULT NULL,
    `url` VARCHAR(256) DEFAULT NULL,
    `req_query` TEXT DEFAULT NULL,
    `req_params` TEXT DEFAULT NULL,
    `req_body` TEXT DEFAULT NULL,
    `res_body` TEXT DEFAULT NULL,
    `headers`  TEXT DEFAULT NULL,
    `ip` VARCHAR(36) DEFAULT NULL,
    `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(37) PRIMARY KEY,
    username VARCHAR(256) NULL,
    email VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_updated DATETIME DEFAULT NULL
) ENGINE=InnoDB;
